//JHOAN RAUL ACOSTA PIEDRAHITA
// 04 DE NOVIEMBRE DEL 2025
// ESTRUCTURA DE CONTROL SELECTIVA SWITCH-CASE 


#include <stdio.h>
int main()
{
char op = '\0'; //DECLARAMOS UNA VARIABLE PARA ALMACENAR LA OPCION SELECCIONADA POR EL USUARIO 
printf("\tMenú\n\n");// IMPRIMIMOS EL MENU DE OPCIONES 
printf("Elegir la opción deseada\n");
printf("a) Ingresar\n");
printf("b) Registrarse\n");
printf("c) Salir\n");
scanf("%c",&op); // LEEMOS LA OPCION INGRESADA POR EL USUARIO Y LA ALMACENAMOS EN LA VARIABLE op
switch(op)// LA SENTENCIA SWITCH EVALUA LA OPCION SELECCIONADA POR EL USUARIO 
{
default:// CASO POR DEFECTO SI NO SE SELECCIONA NINGUNA OPCION VALIDA
printf("Opción no válida.\n");// SI EL USUARIO INGRESA UNA OPCION NO VALIDA, DIFERENTE A ('a', 'b' o 'c')
break; // ASEGURA QUE NO SE EJECUTEN OTRAS SECCIONES DE CODIGO TRS ESTE BLOQUE 
case 'a':// CASO CUANDO EL USUARIO SELECCIONA 'a'
printf("Se seleccionó 'Ingresar'.\n");// EL USUARIO SELECCIONO 'a', SE IMPRIME UN MENSAJE INDICANDO INGRESAR
break;
case 'b':// CASO CUANDO EL USUARIO SELECCIONA 'b'
printf("Se seleccionó 'Registrarse'.\n");// EL USUARIO SELECCIONO 'b', SE IMPRIME UN MENSAJE INDICANDO REGISTRARSE 
break;
case 'c':// CASO CUANDO EL USUARIO SELECCIONA 'c'
printf("Se seleccionó 'Salir'.\n");// EL USUARIO SELECCIONO 'c', SE IMPRIME UN MENSAJE INDICANDO SALIR 
break;
}
return 0;
}
